"""Generates slurm.conf and related config files."""

from typing import List


def generate_slurm_conf(
    controller_host: str,
    node_names: List[str],
    cluster_name: str = "localcluster",
) -> str:
    """Generate a minimal but functional slurm.conf."""

    node_list = ",".join(node_names)

    node_defs = "\n".join(
        f"NodeName={n} CPUs=2 RealMemory=512 Sockets=1 CoresPerSocket=2 ThreadsPerCore=1 State=UNKNOWN"
        for n in node_names
    )

    return f"""# slurm.conf — generated by slurm-local
# See: https://slurm.schedmd.com/slurm.conf.html

ClusterName={cluster_name}
SlurmctldHost={controller_host}

# Authentication
AuthType=auth/munge
CryptoType=crypto/munge

# Scheduling
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory

# Logging
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid

# Spool dirs
StateSaveLocation=/var/spool/slurm
SlurmdSpoolDir=/var/spool/slurmd

# Timeouts
SlurmctldTimeout=120
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0

# Process tracking
ProctrackType=proctrack/pgid
TaskPlugin=task/none

# Return-to-idle
ReturnToService=1

# Job accounting (minimal)
AccountingStorageType=accounting_storage/none
JobAcctGatherType=jobacct_gather/none

# Ports
SlurmctldPort=6817
SlurmdPort=6818

# Mail (disabled)
MailProg=/bin/true

# Nodes
{node_defs}

# Partitions
PartitionName=debug Nodes={node_list} Default=YES MaxTime=INFINITE State=UP
PartitionName=batch Nodes={node_list} Default=NO MaxTime=01:00:00 State=UP
"""


def generate_cgroup_conf() -> str:
    """Generate a minimal cgroup.conf compatible with SLURM 21.08 (Ubuntu 22.04)."""
    return """# cgroup.conf — generated by slurm-local
# Minimal config for Docker-based testing (no real cgroup enforcement)
CgroupAutomount=yes
ConstrainCores=no
ConstrainRAMSpace=no
ConstrainSwapSpace=no
ConstrainDevices=no
"""
